server:
  port: 8888
spring:
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations:
          - file://${user.home}/config-repo
#        git:
#          uri: https://github.com/asharma2/as-cloud-config.git
#          clone-on-start: true
#          username: null
#          password: null
#          basedir: ${user.home}/cloud-config
#          refresh-rate: 5