apiVersion: v1
kind: Service
metadata:
  name: student-aas-svc
  labels:
    app: student-aas
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: student-aas